- id: '1719084998638'
  alias: FrontdoorNotify
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.frontdoorcam
      notify_device: 2e8cc566c26aae1a71ec380470a4c96a
      base_url: https://vahiduk.duckdns.org/
      attachment: snapshot.jpg
      zone_filter: true
      zones:
      - front_steps
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
      debug: true
- id: '1719085120779'
  alias: GarageNotify
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.garagecam
      notify_device: 2e8cc566c26aae1a71ec380470a4c96a
      base_url: https://vahiduk.duckdns.org/
      zone_filter: true
      zones:
      - back_garage
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
- id: '1719085184965'
  alias: SidedoorNotify
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.sidedoorcam
      notify_device: 2e8cc566c26aae1a71ec380470a4c96a
      base_url: https://vahiduk.duckdns.org/
      zone_filter: true
      zones:
      - side_door
      tap_action: '{{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
- id: '1720562297108'
  alias: Turn On Living Room TV with WakeOnLan
  trigger:
  - platform: webostv.turn_on
    entity_id: media_player.lg_webos_smart_tv
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 64:E4:A5:E7:73:B1

- id: '1726044335076'
  alias: Automation:OpenGarage
  description: Open Garage
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: OpenGarage
  condition: []
  action:
  - action: cover.open_cover
    target:
      entity_id: cover.smart_garage_door_1909187155908590801948e1e95224d7_garage
    data: {}
  mode: single

- id: '1726044335077'
  alias: Automation:OpenGarage and Turn Light On
  description: Open Garage and Turn Light On
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: OpenGarageLightOn
  condition: []
  action:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.garagelights_switch_1
  - action: cover.open_cover
    target:
      entity_id: cover.smart_garage_door_1909187155908590801948e1e95224d7_garage
    data: {}
  mode: single

- id: '1726044335078'
  alias: Automation:CloseGarage
  description: Close Garage
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: CloseGarage
  condition: []
  action:
  - action: cover.close_cover
    target:
      entity_id: cover.smart_garage_door_1909187155908590801948e1e95224d7_garage
    data: {}
  mode: single

- id: '1726044335079'
  alias: Automation:CloseGarage and Turn Light Off
  description: Close Garage and Turn Light Off
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: CloseGarageLightOff
  condition: []
  action:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.garagelights_switch_1
  - action: cover.close_cover
    target:
      entity_id: cover.smart_garage_door_1909187155908590801948e1e95224d7_garage
    data: {}
  mode: single

