---
#-
#  _                _
# | | _____   _____| | __ _  ___ ___
# | |/ _ \ \ / / _ \ |/ _` |/ __/ _ \
# | | (_) \ V /  __/ | (_| | (_|  __/
# |_|\___/ \_/ \___|_|\__,_|\___\___|
#
#
#- from github.com/basnijholt/home-assistant-config
- alias: "Lovelace: convert lovelace.json to lovelace-ui.yaml"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: sensor.lovelace
  action:
    - service: shell_command.convert_lovelace
    - service: shell_command.chores  # to update the ASCII art
