---
#-
#                     _ _                  _
#  _ __ ___   ___  __| (_) __ _      _ __ | | __ _ _   _  ___ _ __
# | '_ ` _ \ / _ \/ _` | |/ _` |    | '_ \| |/ _` | | | |/ _ \ '__|
# | | | | | |  __/ (_| | | (_| |    | |_) | | (_| | |_| |  __/ |
# |_| |_| |_|\___|\__,_|_|\__,_|____| .__/|_|\__,_|\__, |\___|_|
#                             |_____|_|            |___/
#
#- from github.com/basnijholt/home-assistant-config

- alias: "Media player: turn on Opt when TV is on and Spotify is not playing and not Usb"
  description: |
    The speaker is connected via an optical cable to the TV. Whenever the speakers
    aren't playing Spotify (via WiFi) directly, switch the source of the speakers
    to "Opt".
  trigger:
    - platform: state
      entity_id: media_player.tv
    - platform: state
      entity_id: media_player.spotify
      to: paused
  condition:
    - condition: state
      entity_id: media_player.tv
      state: "on"
    - "{{ not is_state_attr('media_player.kef_ls50', 'source', 'Optical Input 1') }}"
    - "{{ not is_state_attr('media_player.kef_ls50', 'source', 'HDMI ARC') }}"
    - "{{ not is_state_attr('media_player.tv', 'source', 'GALLERY') }}"
    - >
      {{ not (is_state_attr('media_player.kef_ls50', 'source', 'Usb')
              and is_state_attr('media_player.tv', 'source', 'HDMI 3')) }}
    - >
      {{ not (is_state_attr('media_player.spotify', 'source', 'KEF LS50')
              and is_state('media_player.spotify', 'playing')) }}
  action:
    service: media_player.select_source
    entity_id: media_player.kef_ls50
    data:
      source: Optical Input 1

- alias: "Media player: turn off speakers when turning off TV"
  trigger:
    platform: state
    entity_id: media_player.tv
    to: "off"
  condition:
    condition: state
    entity_id: media_player.kef_ls50
    state: "on"
  action:
    - service: homeassistant.update_entity
      entity_id: media_player.kef_ls50
    - condition: template
      value_template: >
        {{ is_state_attr("media_player.kef_ls50", "source", "HDMI ARC")
           or is_state_attr("media_player.kef_ls50", "source", "Optical Input 1") }}
    - service: media_player.turn_off
      entity_id: media_player.kef_ls50

- alias: "Media player: if speakers off and TV on, turn on the speaker on TV state change"
  trigger:
    platform: state
    entity_id: media_player.tv
  condition: # Happens e.g., when speakers auto-shutdown and the TV is on but idle
    - condition: state
      entity_id: media_player.kef_ls50
      state: "off"
    - condition: state
      entity_id: media_player.tv
      state: "on"
    # only consider meaningful changes to the state
    - >
      {{ trigger.from_state.state != trigger.to_state.state
          or trigger.from_state.attributes["volume_level"] != trigger.to_state.attributes["volume_level"]
          or trigger.from_state.attributes["source"] != trigger.to_state.attributes["source"] }}
  action:
    - service: media_player.turn_on
      entity_id: media_player.kef_ls50
    - service: media_player.select_source
      entity_id: media_player.kef_ls50
      data:
        source: Optical Input 1

- alias: "Media player: update Spotify entity when TV is on every 5 seconds"
  trigger:
    platform: time_pattern
    seconds: "/5"
  condition:
    - condition: state
      entity_id: media_player.spotify
      state: playing
    - condition: state
      entity_id: media_player.tv
      state: "on"
  action:
    service: homeassistant.update_entity
    entity_id: media_player.spotify

- alias: "Media player: sync KEF LS50 and TV volume"
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: media_player.kef_ls50
      attribute: volume_level
    - platform: state
      entity_id: media_player.tv
      attribute: volume_level
  condition:
    - "{{ trigger.to_state.state != 'off' }}"
    - "{{ state_attr('media_player.kef_ls50', 'source') in ('Optical Input 1', 'HDMI ARC', 'Usb') }}"
  action:
    repeat:
      sequence:
        - service: media_player.volume_set
          data:
            entity_id: >
              media_player.{{ "tv" if (trigger.entity_id == "media_player.kef_ls50") else "kef_ls50" }}
            volume_level: >
              {{ state_attr(trigger.entity_id, "volume_level") }}
        - delay:
            milliseconds: 200
      until:
        - >
          {{ state_attr("media_player.tv", "volume_level") == state_attr("media_player.kef_ls50", "volume_level")
              or not (is_state("media_player.tv", "on") and is_state("media_player.kef_ls50", "on")) }}

- alias: "Media player: automatically turn off TV and Xbox after two hours of inactivity"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_living_room_klok
    to: "off"
    for: "02:00:00"
  action:
    - service: media_player.turn_off
      entity_id: media_player.living_room_xbox
    - service: media_player.turn_off
      entity_id: media_player.tv

- alias: "Media player: Turn On Living Room TV with WakeOnLan"
  trigger:
    platform: webostv.turn_on
    entity_id: media_player.tv
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: "!secret tv_mac_address"
