---
#-
#                _
#  ___ _   _ ___| |_ ___ _ __ ___
# / __| | | / __| __/ _ \ '_ ` _ \
# \__ \ |_| \__ \ ||  __/ | | | | |
# |___/\__, |___/\__\___|_| |_| |_|
#      |___/
#
#- from github.com/basnijholt/home-assistant-config
- alias: "System: warning about high CPU usage"
  trigger:
    platform: numeric_state
    entity_id: sensor.processor_use
    above: 70
    for:
      hours: 4
  action:
    service: notify.iphone_bas
    data:
      title: "System"
      message: "CPU usage has been above 70% for 4 hours! ⚠️🖥"

- alias: "System: warning about high CPU temperature"
  trigger:
    platform: numeric_state
    entity_id: sensor.cpu_temperature
    above: 70
    for:
      hours: 4
  action:
    service: notify.iphone_bas
    data:
      title: "System"
      message: "CPU temperature has been above 70 °C for 4 hours! ⚠️"

- alias: "System: warning about high Xbox temperature"
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_xbox
    above: 50
  action:
    - service: notify.iphone_bas
      data:
        title: "System"
        message: >
          Temperature in the Xbox cabinet is {{ states("sensor.temperature_xbox") }} °C! ⚠️
    - condition: state
      entity_id: media_player.tv
      state: "on"
    - service: notify.tv
      data:
        message: >
          Temperature in the Xbox cabinet is {{ states("sensor.temperature_xbox") }} °C! ⚠️

- alias: "System: run chores"
  description: Run shell and Python scripts in utils folder.
  trigger:
    platform: time_pattern
    minutes: "/15"
  action:
    service: shell_command.chores

- alias: "System: MQTT sensors are not updating"
  description: Check whether we are receiving messages over MQTT from my other HA instance.
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition: "{{ (as_timestamp(now()) - as_timestamp(states.sensor.power_consumption.last_changed)) > 20 * 60 }}"
  action:
    - service: notify.iphone_bas
      data:
        title: "System"
        message: "Not receiving MQTT updates, maybe reboot the other HA instance! ⚠️"
    - delay: "03:00:00"  # don't tell me again for three hours

- alias: "System: battery level low"
  trigger:
    platform: time
    at: "14:30:00"
  variables:
    min_battery_level: 50
    notify_service: notify.iphone_bas
    battery_ids: ""
    current: ""
  action:
    - variables:
        battery_ids: >
          {% set ns = namespace(battery=[]) %}
          {% for s in states.sensor if 'battery_level' in s.entity_id %}
            {% set ns.battery = ns.battery + [s] %}
          {% endfor %}
          {{ ns.battery | map(attribute='entity_id') | list }}
    - alias: Repeat
      repeat:
        count: "{{ battery_ids | length }}"
        sequence:
          - variables:
              current: "{{ battery_ids[repeat.index - 1] }}"
          - condition: template
            value_template: "{{ 'iphone' not in current and 'ipad' not in current }}"
          - condition: template
            value_template: "{{ 0 < (states(current) | float) < (min_battery_level | float ) }}"
          - service: "{{ notify_service }}"
            data:
              title: "System"
              message: "Battery level low of {{ current }}: {{ states(current) }}%! ⚠️"
