---
#-
#                     _ _                  _
#  _ __ ___   ___  __| (_) __ _      _ __ | | __ _ _   _  ___ _ __ ___
# | '_ ` _ \ / _ \/ _` | |/ _` |    | '_ \| |/ _` | | | |/ _ \ '__/ __|
# | | | | | |  __/ (_| | | (_| |    | |_) | | (_| | |_| |  __/ |  \__ \
# |_| |_| |_|\___|\__,_|_|\__,_|____| .__/|_|\__,_|\__, |\___|_|  |___/
#                             |_____|_|            |___/
#
#- from github.com/basnijholt/home-assistant-config

- platform: bluesound
  hosts:
    - host: 192.168.1.241
      name: KEF LS50
