---
#-
#              _   _  __
#  _ __   ___ | |_(_)/ _|_   _
# | '_ \ / _ \| __| | |_| | | |
# | | | | (_) | |_| |  _| |_| |
# |_| |_|\___/ \__|_|_|  \__, |
#                        |___/
#
#
- platform: group
  name: all_iphones
  services:
    - service: mobile_app_vahids_iphone
    - service: mobile_app_maryams_iphone

- platform: group
  name: vahid
  services:
    - service: mobile_app_vahids_iphone
    - service: chrome

- platform: group
  name: iphone_vahid
  services:
    - service: mobile_app_vahids_iphone

- platform: group
  name: all
  services:
    - service: mobile_app_vahids_iphone
    - service: mobile_app_maryams_iphone
    - service: tv
    - service: chrome

- platform: html5
  name: chrome
  vapid_pub_key: !secret firebase_public_key
  vapid_prv_key: !secret firebase_private_key
  vapid_email: !secret firebase_service_account
